# Generated by Django 3.0.4 on 2020-04-11 03:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    replaces = [('contests', '0001_initial'), ('contests', '0002_auto_20200410_1324'), ('contests', '0003_auto_20200410_1511')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('start', models.DateTimeField(null=True)),
                ('end', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'contests',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=2048)),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=15)),
                ('vs_liveshare_link', models.CharField(max_length=2048)),
                ('github_branch_name', models.CharField(max_length=50)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contests')),
            ],
            options={
                'db_table': 'teams',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='contests',
            name='tasks',
            field=models.ManyToManyField(to='contests.Tasks'),
        ),
    ]
