# Generated by Django 3.0.4 on 2020-04-11 06:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0001_squashed_0003_auto_20200410_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskSubmissions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('point', models.IntegerField(default=0)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Tasks')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Teams')),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-date_created', 'id'],
            },
        ),
        migrations.AddField(
            model_name='teams',
            name='submissions',
            field=models.ManyToManyField(through='contests.TaskSubmissions', to='contests.Tasks'),
        ),
    ]
