# Generated by Django 3.0.5 on 2020-04-12 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_auto_20200411_0609'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestsTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField()),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Contests')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contests.Tasks')),
            ],
            options={
                'db_table': 'contests_tasks_ordering',
                'ordering': ['contest', 'ordering'],
            },
        ),
        migrations.RemoveField(
            model_name='contests',
            name='tasks'
        ),
        migrations.AddField(
            model_name='contests',
            name='tasks',
            field=models.ManyToManyField(through='contests.ContestsTasks', to='contests.Tasks'),
        ),
    ]
