# Generated by Django 3.0.5 on 2020-04-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20200412_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmissions',
            name='point',
            field=models.IntegerField(null=True),
        ),
    ]
