# Generated by Django 3.0.5 on 2020-04-13 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='link',
            field=models.CharField(max_length=2048, null=True),
        ),
    ]
