# Generated by Django 3.0.5 on 2020-04-14 07:39

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_questions_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=8192)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('task', models.ManyToManyField(null=True, to='contests.Tasks')),
            ],
            options={
                'db_table': 'hints',
                'ordering': ['-date_created', 'id'],
            },
        ),
    ]
