# Generated by Django 3.0.5 on 2020-04-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0007_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='title',
            field=models.CharField(default='質問', max_length=512),
        ),
    ]
