name: CI
on:
  push:
    branches:
      - master
    paths:
      - 'front/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/build-and-deploy.yml'

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd front install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd front build
      - name: Publish to AWS S3
        uses: opspresso/action-s3-sync@master
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-northeast-1"
          FROM_PATH: "./front/dist/"
          DEST_PATH: ${{ secrets.AWS_OUTPUT_S3_URI }}
          OPTIONS: "--follow-symlinks --delete"
