name: CI
on:
  pull_request:
    branches:
      - master
    paths:
      - 'front/**'
      - '.github/workflows/build.yml'
      - '.github/workflows/build-and-deploy.yml'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd front install
      - uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd front build
